/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../common/game.h"
#include "assets_file_io.h"
#include <android/log.h>
// for native asset manager
#include <assert.h>
#include <sys/types.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <jni.h>
/* Header for class com_opengltutorial_opengles2tutorial_GameLibJNIWrapper */

#ifndef _Included_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
#define _Included_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
 * Method:    load
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_load
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv *, jclass);

/*
 * Class:     com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass);

/*
 * Class:     com_opengltutorial_opengles2tutorial_GameLibJNIWrapper
 * Method:    on_touch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1touch
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_load
  (JNIEnv * env, jclass, jobject assetManager){
	AAssetManager* mgr = AAssetManager_fromJava(env, assetManager);
	assert(NULL != mgr);
	android_fopen_set_asset_manager(mgr);
}

JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1surface_1created
(JNIEnv * env, jclass cls) {
//	g_env = env; // global variables, containing assets info
//	__android_log_print(ANDROID_LOG_VERBOSE, "test", "init gl");
	set_vertshader_file(android_fopen((const char*) "simplevert.vert", (const char*)"r"));
	set_fragshader_file(android_fopen((const char*) "simplefrag.frag", (const char*)"r"));
//	__android_log_print(ANDROID_LOG_VERBOSE, "test", "pass shader files done");
	on_surface_created();
}

JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1surface_1changed
(JNIEnv * env, jclass cls, jint width, jint height) {
	int w = width;
	int h = height;
	on_surface_changed(w, h);
}

JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1draw_1frame
(JNIEnv * env, jclass cls) {
	on_draw_frame();
}

JNIEXPORT void JNICALL Java_com_opengltutorial_opengles2tutorial_GameLibJNIWrapper_on_1touch
(JNIEnv * env, jclass cls) {
	on_touch();
}

#ifdef __cplusplus
}
#endif
#endif
